### PR TITLE
Revamped QMD for Milestone 3

### PR DESCRIPTION
**Pull request by derekrodgers**
Previously in this branch, we created the modular analysis scripts.

With my final commit, we've impemented all of the changes necessary to the QMD file to have it use the analysis artifacts rendered out by the scripts, and removed all visible code chunks. We've also implemented figure numbering and cross-referencing, and a Bibtex bibliography.

Finally, I've switched us from a default PDF output to HTML, since it has fewer rendering issues and will enable us to use GH pages more easily later on.

### CODE REVIEW

**Comment by derekrodgers** [comment]
I accidentally merged this on my own, sorry! But @ZhengHe-007 could you give it a look anyway to make sure we don't need to roll anything back?

**Comment by ZhengHe-007** [comment]
I thought we can discuss on if we need a title  for the chart here, i noticed you put the figure name under the chart which is fine.

**Comment by ZhengHe-007** [comment]
Also in the qmd file under References is empty but it shows up on HTML, is it normal?

**Comment by derekrodgers** [comment]
The chart title should be in the caption as that's how we were taught to do it in the lecture this week I am pretty sure

The references automatically render at the bottom of the file. There is no need to add any marker to cause them to show up.

**Comment by ZhengHe-007** [comment]
> The chart title should be in the caption as that's how we were taught to do it in the lecture this week I am pretty sure
> 
> The references automatically render at the bottom of the file. There is no need to add any marker to cause them to show up.

Nice, everything else looks great!

**Pull request merged**
